K-Core for graphology
graphology/graphology pull request #486
Opened 2023-07-17 13:12 UTC by 16arpi

Implementation of the degeneracy calculation already available in the `networkx` python library. It adds to graphology the following methods : 

* coreNumber()
* kCore()
* kShell()
* kCrust()
* kCorona()
* onionLayers()

However, it doesn't include the method `kTruss()`.

The pull request includes tests, a package description and a readme documentation. 

The typescript description file `index.d.ts` needs to be written.

For more details of the original python implementation : [https://networkx.org/documentation/stable/reference/algorithms/core.html](https://networkx.org/documentation/stable/reference/algorithms/core.html)

2023-07-19 09:36 UTC, Yomguithereal commented on src/cores/README.md
> +- **coreAttribute** _?string_ : the name of the attribute to use if core numbers are assigned to the nodes.
`nodeCoreAttribute` pour être cohérent avec les autres APIs.

2023-07-19 09:36 UTC, Yomguithereal commented on src/cores/README.md
> +- **onionLayerAttribute** _?string_ : the name of the attribute to use if onion layers are assigned to the nodes.
`nodeOnionLayerAttribute`

2023-07-21 08:59 UTC, Yomguithereal requested changes

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +  const nodes = Object.entries(degrees)
Plutôt trier `graph.nodes()`

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +  const binBounderie = [0];
Peut-être utiliser un array typé de type fixe.

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +      graph.forEachInboundNeighbor(node, nbr => {
`forEachInNeighbor`

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +        const binStart = binBounderie[core[nbr]];
orthographe

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +    graph.forEachNode(node => {
Utiliser graph.updateEachNodeAttributes

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +    k = Math.max.apply(Math, Object.values(customCore));
Nope. Ne pas utiliser Object.values et ne pas utiliser apply.

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +  Object.entries(customCore).forEach(pair => {
Ne pas utiliser de callback, faire un for in

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +    (cv, ck, cc) => {
Ya des noms plus clairs?

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +    k = Math.max.apply(Math, Object.values(customCore)) - 1;
Idem

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +  Object.entries(customCore).forEach(pair => {
Idem

2023-07-21 08:59 UTC, Yomguithereal commented on src/cores/index.js
> +          graph.inboundNeighbors(cv).reduce((acc, nb) => {
`inNeighbors`

2024-03-26 11:12 UTC, AlexisPister commented
Is there something more to do on this PR? I would need to use k-cores on a project using Graphology. Happy to contribute if needed.

2024-03-27 09:32 UTC, Yomguithereal commented
@AlexisPister will merge and try to release soon.

@16arpi tu vois j'avais dit que je mergerai un jour :)

2024-03-27 09:32 UTC, merged

2024-03-27 10:13 UTC, 16arpi commented
> @16arpi tu vois j'avais dit que je mergerai un jour :)

Je n'ai jamais perdu espoir ahah !

2024-03-27 10:55 UTC, Yomguithereal commented
@AlexisPister `graphology-cores` was just published on npm. Docs can be found here: https://graphology.github.io/standard-library/cores

Can you tell me whether this fits your use cases?

2024-03-27 11:45 UTC, AlexisPister commented
> @AlexisPister `graphology-cores` was just published on npm. Docs can be found here: https://graphology.github.io/standard-library/cores
> 
> Can you tell me whether this fits your use cases?

Thanks! I'll try this soon and let you know.